-- 코드를 작성해주세요
SELECT A.EMP_NO AS EMP_NO, EMP_NAME,
    CASE
        WHEN SCORE >= 96 THEN "S"
        WHEN SCORE >= 90 THEN "A"
        WHEN SCORE >= 80 THEN "B"
        ELSE "C"
    END AS GRADE,
    CASE
        WHEN SCORE >= 96 THEN SAL * (20 / 100)
        WHEN SCORE >= 90 THEN SAL * (15 / 100)
        WHEN SCORE >= 80 THEN SAL * (10 / 100)
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES AS A
LEFT JOIN (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS B
ON A.EMP_NO = B.EMP_NO
ORDER BY EMP_NO;